### ISSUE TITLE
Mode 수정사항

### ISSUE THREAD

**Issue by lm9204** [TFTrc/TFTirc#120]
- topic 권한에 대해서 작동안함

**Comment by JeongTJ** [comment]
토픽권한 작동하는것으로 확인됩니다.
정확히 어떤 경우에 안되는지 알 수 있을까요?

t모드가 존재할 시 오퍼레이터만 수정 가능해지고, t모드가 없을 땐 채널의 모두가 토픽을 수정할 수 있습니다.

**Comment by lm9204** [comment]
확인했습니다 이전 커밋에서 발생되었던 부분이었는데 해결되었네요.
