### ISSUE TITLE
Client 객체 추가 필요 사항

### ISSUE THREAD

**Issue by duckgii** [TFTrc/TFTirc#16]
- [ ] flag가 있어야 한다
    - NICK, USER은 PASS가 실행된 후 실행되어야 하므로 PASS 실행 전에는 flag를 0으로 두고 실행 후에는 1로 바꾼다.
    - NICK, USER을 제외한 다른 커맨드는(ex. JOIN...) NICK, USER이 호출된 후 실행되어야 하므로, NICK, USER을 실행하면 flag를 1씩 증가하여,
    - 다른 커맨드는 flag의 값이 3 이상일 때만 실행되도록 한다.
    - NICK, USER도 비슷한 로직으로 순서를 구현한다.
    - 올바른 순서가 아닌 명령어가 들어오면 프로토콜에 따라서 메세지를 보낸다.
- [x] 유저이름 반환 메서드가 필요 getUserName()
- [x] nickName필드의 초기값을 "*" 로 해줄 필요가 있음.
    - 아직 nickName이 정해지지 않은 상태에서 <client> 필드를 채우기 위해선 * 문자를 넣어줘야함.

**Comment by lm9204** [comment]
1번 사항은 Client 객체가 초기값이 빈 문자열로 할당되는데 각 커맨드가 파싱되어서 진행되었다면 Username, Hostname, Realname 각 3필드가 차있을텐데 그 부분을 확인하면서 플래그를 대체하는게 어떨까 싶습니다. 
2번 부분은 이미 존재합니다
- who() -> nick!nick@host.com
- getNickName() -> nick
- getHostName()
- getRealName()
