### ISSUE TITLE
JOIN 커맨드 수정사항

### ISSUE THREAD

**Issue by lm9204** [TFTrc/TFTirc#84]
- JOIN시에 채널이 존재하지 않을 경우 만들고 나서 만든 client에게 권한설정해줘야함 `setOper()`

**Comment by JeongTJ** [comment]
채널 생성시 setOper()을 수행하기 때문에 별도로 처리하지 않았습니다.

**Comment by JeongTJ** [comment]
채널 생성시 setOper() 메서드가 작동하지 않습니다.
외부에서 오퍼레이터를 추가하게 하려면 생성자에서 setOper() 부분은 빼야할것 같습니다.
